import type { TaskRecord } from "../storage/schema";
import type { SpecRecord } from "../storage/spec-store";
import { specRequirementSubject } from "./spec-compiler";

/**
 * Deterministic plan-coverage compiler (SPEC.md REQ-4b/4c): from `spec.json`
 * plus each task's `requirements` traceability list it emits the Skolem
 * witness tables the coverage gate runs:
 *
 * - `TOTAL covered_by ON requirements` — every in-scope, non-deferred
 *   requirement must be the subject of at least one `covered_by` pair; the
 *   engine NAMES each dropped requirement.
 * - `TOTAL traces ON tasks` — every task must trace to at least one
 *   requirement; the engine NAMES each orphan task.
 *
 * Requirements discharged through the freedom valve (deferral) and non-goals
 * never enter the requirement set (REQ-3, §2.2): a deferral IS the discharge.
 *
 * The program is fully self-contained (no template import): elenchus SETs are
 * data and do not cross files, so the sets, the witness pairs, and the TOTAL
 * lines must live in one generated file. That is fine — this program is
 * compiler-authored end to end (REQ-12), there is nothing for a model to get
 * wrong. Plain `CHECK` suffices: everything here is data, and TOTAL is a
 * compile-time scan.
 */

export interface CompiledPlanCoverage {
	program: string;
	/** Maps a VRF task subject back to the real taskId, for gap reporting. */
	taskSubjects: Record<string, string>;
	requirementCount: number;
	taskCount: number;
	/** Requirements a task cites that the spec does not know (hard error upstream). */
	unknownRequirementRefs: Array<{ taskId: string; requirement: string }>;
}

/** `fix-storage-root` → `task_fix_storage_root` (collision-checked). */
function taskSubjectFor(taskId: string, used: Set<string>): string {
	const base = `task_${taskId.toLowerCase().replace(/[^a-z0-9_]+/g, "_")}`;
	let candidate = base;
	let suffix = 2;
	while (used.has(candidate)) {
		candidate = `${base}_${suffix}`;
		suffix += 1;
	}
	used.add(candidate);
	return candidate;
}

export function compilePlanCoverage(
	spec: SpecRecord,
	tasks: readonly TaskRecord[],
): CompiledPlanCoverage {
	const coverable = [...spec.requirements]
		.filter((req) => req.inScope && req.deferral === undefined)
		.sort((a, b) => a.id.localeCompare(b.id, "en", { numeric: true }));
	const orderedTasks = [...tasks].sort((a, b) =>
		a.taskId.localeCompare(b.taskId, "en", { numeric: true }),
	);

	const knownRequirementIds = new Set(spec.requirements.map((req) => req.id));
	const usedSubjects = new Set<string>();
	const taskSubjects: Record<string, string> = {};
	const unknownRequirementRefs: CompiledPlanCoverage["unknownRequirementRefs"] =
		[];

	const lines: string[] = [
		"// Generated by pi-code-planner's deterministic coverage compiler from",
		"// spec.json + the tasks' requirements traceability. Do not edit by hand.",
		"DOMAIN plan_coverage",
		"",
	];

	if (coverable.length > 0) {
		lines.push("SET requirements");
		for (const req of coverable) {
			lines.push(`    ${specRequirementSubject(req.id)}`);
		}
		lines.push("");
	}
	if (orderedTasks.length > 0) {
		lines.push("SET tasks");
		for (const task of orderedTasks) {
			const subject = taskSubjectFor(task.taskId, usedSubjects);
			taskSubjects[subject] = task.taskId;
			lines.push(`    ${subject}`);
		}
		lines.push("");
	}

	const coverableIds = new Set(coverable.map((req) => req.id));
	for (const task of orderedTasks) {
		const subject = Object.keys(taskSubjects).find(
			(key) => taskSubjects[key] === task.taskId,
		) as string;
		for (const requirement of [...(task.requirements ?? [])].sort()) {
			if (!knownRequirementIds.has(requirement)) {
				unknownRequirementRefs.push({ taskId: task.taskId, requirement });
				continue;
			}
			// A pair citing a deferred/out-of-scope requirement still counts as
			// the task's own trace, but only coverable requirements are totaled.
			const reqSubject = specRequirementSubject(requirement);
			if (coverableIds.has(requirement)) {
				lines.push(`FACT ${reqSubject} covered_by ${subject}`);
			}
			lines.push(`FACT ${subject} traces ${reqSubject}`);
		}
	}
	lines.push("");

	if (coverable.length > 0) {
		lines.push("TOTAL covered_by ON requirements");
	}
	if (orderedTasks.length > 0) {
		lines.push("TOTAL traces ON tasks");
	}
	lines.push("", "CHECK");

	return {
		program: `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`,
		taskSubjects,
		requirementCount: coverable.length,
		taskCount: orderedTasks.length,
		unknownRequirementRefs,
	};
}
