import type { SpecRecord } from "../storage/spec-store";

/**
 * Deterministic spec→VRF compiler (SPEC.md REQ-4/REQ-12): turns a validated
 * `spec.json` into the program the spec-consistency gate runs. The model never
 * hand-writes this — every sharp edge of the DSL lives here, in tested code.
 *
 * Compilation model (mirrors the engine-verified freedom-valve arc bundled as
 * vrf/defaults/spec-consistency.vrf):
 *
 * - Every in-scope requirement becomes a fully *closed* subject in the
 *   template's domain: `is_requirement` plus the formalized / deferred triple
 *   asserted explicitly (FACT or NOT, never omitted), so `CHECK BIDIRECTIONAL`
 *   finds no artificial alternative models — a surviving UNDERDETERMINED or
 *   WARNING is a real spec gap, not compiler noise.
 * - Assumptions (§2.1 boolean leaves) become `FACT <atom> holds` / `NOT` in
 *   the local domain. Numbers never appear; the atom carries the verdict of a
 *   predicate the model computed outside the fence.
 * - Constraint relations become PREMISE blocks over the same `<atom> holds`
 *   leaves. A constraint referencing an atom nothing establishes yields a
 *   WARNING naming it — that warning is the elicit-gaps interview script.
 * - Each declared acceptance atom becomes an advisory `PROVE`, so the report
 *   records which acceptance criteria are already derivable (usually none at
 *   the spec stage — they are discharged by later stages).
 *
 * Output is byte-deterministic: requirements/constraints/assumptions are
 * sorted by id, and the engine itself is deterministic, so snapshots are safe.
 */

export interface CompiledSpecCheck {
	/** The entry program; imports the bundled spec-consistency template. */
	program: string;
	/** VAR port bindings to pass alongside the program. */
	values: Record<string, boolean>;
	/** How many in-scope requirements were compiled. */
	requirementCount: number;
}

/** `REQ-3` → the VRF subject `req_3`. */
export function specRequirementSubject(id: string): string {
	return id.toLowerCase().replace(/-/g, "_");
}

/** Reverse of {@link specRequirementSubject}, for gap reporting. */
export function specSubjectToRequirementId(subject: string): string {
	const match = /^req_(\d+)$/.exec(subject);
	return match ? `REQ-${match[1]}` : subject;
}

function byId<T extends { id: string }>(items: readonly T[]): T[] {
	return [...items].sort((a, b) =>
		a.id.localeCompare(b.id, "en", { numeric: true }),
	);
}

function leaf(ref: string): string {
	return ref.startsWith("!") ? `NOT  ${ref.slice(1)} holds` : `${ref} holds`;
}

export function compileSpecConsistency(spec: SpecRecord): CompiledSpecCheck {
	const lines: string[] = [
		"// Generated by pi-code-planner's deterministic spec→VRF compiler from",
		"// spec.json — do not edit by hand; re-run planner_gate_check instead.",
		"DOMAIN spec_check",
		'IMPORT "templates/spec-consistency.vrf"',
		"",
	];

	const inScope = byId(spec.requirements.filter((req) => req.inScope));
	for (const req of inScope) {
		const subject = `spec_gate.${specRequirementSubject(req.id)}`;
		lines.push(`// ${req.id}: ${req.statement}`);
		lines.push(`FACT ${subject} is_requirement`);
		if (req.acceptanceAtom !== undefined) {
			lines.push(`FACT ${subject} formalized`);
			lines.push(`FACT ${subject} vrf_expressible`);
			lines.push(`NOT  ${subject} rationale_recorded`);
			lines.push(`NOT  ${subject} deferred_to_freedom`);
		} else {
			// Freedom valve (§2.2): validated to carry a rationale at submit time;
			// `deferred_to_freedom` is derived by the template's valve rule.
			lines.push(`NOT  ${subject} formalized`);
			lines.push(`NOT  ${subject} vrf_expressible`);
			lines.push(`FACT ${subject} rationale_recorded`);
		}
		lines.push("");
	}

	const assumptions = byId(spec.assumptions);
	if (assumptions.length > 0) {
		lines.push("// assumptions — boolean leaves with recorded evidence");
		for (const asm of assumptions) {
			lines.push(
				`${asm.negated ? "NOT " : "FACT"} ${asm.atom} holds // ${asm.id}`,
			);
		}
		lines.push("");
	}

	const constraints = byId(spec.constraints).filter(
		(con) => con.relation !== undefined,
	);
	for (const con of constraints) {
		const relation = con.relation;
		if (!relation) continue;
		const name = con.id.toLowerCase().replace(/-/g, "_");
		lines.push(`// ${con.id}: ${con.statement}`);
		if (relation.type === "implies") {
			lines.push(`PREMISE ${name}:`);
			relation.when.forEach((ref, index) => {
				lines.push(`    ${index === 0 ? "WHEN" : "AND "} ${leaf(ref)}`);
			});
			lines.push(`    THEN ${leaf(relation.then)}`);
		} else {
			const keyword =
				relation.type === "exclusive"
					? "EXCLUSIVE"
					: relation.type === "oneof"
						? "ONEOF"
						: "ATLEAST";
			lines.push(`PREMISE ${name}:`);
			lines.push(`    ${keyword}`);
			for (const atom of relation.atoms) {
				lines.push(`    ${atom} holds`);
			}
		}
		lines.push("");
	}

	const goals = inScope.filter((req) => req.acceptanceAtom !== undefined);
	if (goals.length > 0) {
		lines.push(
			"// acceptance goals (advisory: usually OPEN at the spec stage)",
		);
		for (const req of goals) {
			lines.push(`PROVE ${req.acceptanceAtom} holds // ${req.id}`);
		}
		lines.push("");
	}

	lines.push("CHECK BIDIRECTIONAL");
	return {
		program: `${lines.join("\n")}\n`,
		values: { "spec_gate.spec_verified": true },
		requirementCount: inScope.length,
	};
}
