import type { TaskBehaviorsRecord } from "../storage/behavior-store";
import { specRequirementSubject } from "./spec-compiler";

/**
 * Deterministic behaviors.json → VRF compiler for the tdd_coverage gate.
 *
 * Every behavior is one element of `SET behaviors`; a red test contributes a
 * `has_red_test` witness pair, a green one additionally `has_green_test`.
 * `TOTAL … ON behaviors` then NAMES every behavior that still lacks the
 * phase's witness — the machine's to-do list, not the model's belief:
 *
 * - phase "red"   (write_tests / run_failing_tests): every behavior needs a
 *   named failing test.
 * - phase "green" (run_final_tests): every behavior needs BOTH witnesses —
 *   the red total keeps test-first visible even at the end.
 *
 * When the task owns spec requirements, a second witness table binds the two:
 * `TOTAL covered_by ON requirements` NAMES every REQ-n the task discharges that
 * no behavior exercises — activating behaviors' spec traceability instead of
 * trusting the model listed enough behaviors (a REQ with no behavior is a hole,
 * not silence). A behavior citing a requirement the task does not own is a
 * hard error surfaced through `unknownRequirementRefs`.
 *
 * Plain CHECK: the program is pure data, TOTAL is a compile-time scan.
 */

export type TddCoveragePhase = "red" | "green";

export interface CompileTddCoverageOptions {
	/**
	 * The in-scope, non-deferred REQ-n ids this task owns (task.requirements ∩
	 * spec). Empty for legacy plans without a spec — the requirement dimension is
	 * then omitted and only behavior coverage is checked.
	 */
	ownedRequirements?: readonly string[];
}

export interface CompiledTddCoverage {
	program: string;
	/** Maps a VRF behavior subject back to the BHV-n id, for gap reporting. */
	behaviorSubjects: Record<string, string>;
	behaviorCount: number;
	requirementCount: number;
	/** Behaviors citing a requirement the task does not own (hard error upstream). */
	unknownRequirementRefs: Array<{ behaviorId: string; requirement: string }>;
	phase: TddCoveragePhase;
}

/** `BHV-3` → `bhv_3`. */
export function behaviorSubject(id: string): string {
	return id.toLowerCase().replace(/-/g, "_");
}

export function compileTddCoverage(
	record: TaskBehaviorsRecord,
	phase: TddCoveragePhase,
	options: CompileTddCoverageOptions = {},
): CompiledTddCoverage {
	const behaviors = [...record.behaviors].sort((a, b) =>
		a.id.localeCompare(b.id, "en", { numeric: true }),
	);
	const ownedRequirements = [...(options.ownedRequirements ?? [])].sort(
		(a, b) => a.localeCompare(b, "en", { numeric: true }),
	);
	const ownedSet = new Set(ownedRequirements);
	const unknownRequirementRefs: CompiledTddCoverage["unknownRequirementRefs"] =
		[];
	const behaviorSubjects: Record<string, string> = {};
	const lines: string[] = [
		"// Generated by pi-code-planner's deterministic tdd-coverage compiler",
		`// from tasks/${record.taskId}/behaviors.json. Do not edit by hand.`,
		"DOMAIN tdd_coverage",
		"",
		"SET behaviors",
	];
	for (const behavior of behaviors) {
		const subject = behaviorSubject(behavior.id);
		behaviorSubjects[subject] = behavior.id;
		lines.push(`    ${subject}`);
	}
	lines.push("");
	if (ownedRequirements.length > 0) {
		lines.push("SET requirements");
		for (const requirement of ownedRequirements) {
			lines.push(`    ${specRequirementSubject(requirement)}`);
		}
		lines.push("");
	}
	for (const behavior of behaviors) {
		const subject = behaviorSubject(behavior.id);
		const test = behavior.test
			? `${behavior.test.file} :: ${behavior.test.name}`
			: "";
		if (behavior.status === "red" || behavior.status === "green") {
			lines.push(`FACT ${subject} has_red_test witnessed // ${test}`);
		}
		if (behavior.status === "green") {
			lines.push(`FACT ${subject} has_green_test witnessed // ${test}`);
		}
		if (behavior.requirement) {
			if (ownedSet.has(behavior.requirement)) {
				lines.push(
					`FACT ${specRequirementSubject(behavior.requirement)} covered_by ${subject}`,
				);
			} else {
				unknownRequirementRefs.push({
					behaviorId: behavior.id,
					requirement: behavior.requirement,
				});
			}
		}
	}
	lines.push("");
	lines.push("TOTAL has_red_test ON behaviors");
	if (phase === "green") {
		lines.push("TOTAL has_green_test ON behaviors");
	}
	if (ownedRequirements.length > 0) {
		lines.push("TOTAL covered_by ON requirements");
	}
	lines.push("", "CHECK");
	return {
		program: `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`,
		behaviorSubjects,
		behaviorCount: behaviors.length,
		requirementCount: ownedRequirements.length,
		unknownRequirementRefs,
		phase,
	};
}
